navikt/pleiepengesoknad-api

- nais/dev-sbs.yml
- nais/prod-sbs.yml
- src/main/kotlin/no/nav/helse/App.kt
- src/main/kotlin/no/nav/helse/Configuration.kt
- src/main/kotlin/no/nav/helse/vedlegg/K9DokumentGateway.kt
- src/main/kotlin/no/nav/helse/vedlegg/VedleggService.kt
- src/main/resources/application.conf
- src/test/kotlin/no/nav/helse/ApplicationTest.kt
- src/test/kotlin/no/nav/helse/ApplicationWithMocks.kt
- src/test/kotlin/no/nav/helse/TestConfiguration.kt
- src/test/kotlin/no/nav/helse/wiremock/K9DokumentResponseTransformer.kt
- src/test/kotlin/no/nav/helse/wiremock/WireMockStubs.kt
Renames all references to pleiepenger-dokument to k9-dokument.
> Refactors pleiepenger-dokument to k9-dokument

- .github/workflows/build-and-deploy.yml
- nais/dev-sbs.yml
- nais/prod-sbs.yml
Migrer til nais-deploy action og simplifiserer ci/cd fil.
Fjerner jobb for trigging av workflow via deployment.
Flytter miljøvariabler til globale miljøvariabler i workflow.
> Migrer til nais-deploy 

- src/main/kotlin/no/nav/helse/barn/Barn.kt
- src/main/kotlin/no/nav/helse/barn/BarnGateway.kt
- src/main/kotlin/no/nav/helse/barn/BarnService.kt
- src/test/kotlin/no/nav/helse/ApplicationTest.kt
- src/test/kotlin/no/nav/helse/wiremock/BarnResponseTransformer.kt
Legger til "har_samme_adresse" på oppslag av barn fra k9-selvbetjening-oppslag.
> Legger til felt for "har_samme_adresse" på barnoppslag fra k9-selvb.-op.

- README.md
- src/main/kotlin/no/nav/helse/soknad/KomplettSoknad.kt
- src/main/kotlin/no/nav/helse/soknad/Soknad.kt
- src/main/kotlin/no/nav/helse/soknad/SoknadService.kt
- src/main/kotlin/no/nav/helse/soknad/SoknadValidator.kt
- src/test/kotlin/no/nav/helse/ApplicationTest.kt
- src/test/kotlin/no/nav/helse/ArbeidsgiverValidationTest.kt
- src/test/kotlin/no/nav/helse/SoknadUtils.kt
- src/test/kotlin/no/nav/helse/SoknadValidationTest.kt
Oppdaterer/fjerner valideringer som har brukt grad.
Oppdaterer tester.
> Fjerner grad da dette er utgått og ikke brukes lenger.

- README.md
- src/main/kotlin/no/nav/helse/soknad/KomplettSøknad.kt
- src/main/kotlin/no/nav/helse/soknad/SoknadService.kt
- src/main/kotlin/no/nav/helse/soknad/Søknad.kt
- src/test/kotlin/no/nav/helse/ApplicationTest.kt
- src/test/kotlin/no/nav/helse/SerDesTest.kt
- src/test/kotlin/no/nav/helse/SoknadUtils.kt
- src/test/kotlin/no/nav/helse/SoknadValidationTest.kt
Prosessering må være oppdatert før api oppdateres.
> Fjerner ubrukt kode. Frontend sender ikke inn, og brukes ikke i pdf.

- src/main/kotlin/no/nav/helse/App.kt
> Tillater http PUT requests

- .github/workflows/build-and-deploy.yml
- build.gradle.kts
> Oppdaterer cache og kotlin jvm.

- src/main/kotlin/no/nav/helse/mellomlagring/MellomlagringService.kt
- src/main/kotlin/no/nav/helse/redis/RedisStore.kt
- src/test/kotlin/no/nav/helse/mellomlagring/MellomlagringTest.kt
> Renamer TTL metode.

- nais/dev-sbs.json
- src/main/kotlin/no/nav/helse/soknad/ArbeidsgiverDetaljer.kt
- src/main/kotlin/no/nav/helse/soknad/KomplettSøknad.kt
- src/main/kotlin/no/nav/helse/soknad/SøknadService.kt
- src/main/kotlin/no/nav/helse/soknad/SøknadValidator.kt
- src/test/kotlin/no/nav/helse/ArbeidsgiverValidationTest.kt
- src/test/kotlin/no/nav/helse/SoknadValidationTest.kt
Fjerner optional på harVærtEllerErVernepliktig i KomplettSøknad og setter på validering.
Setter på test som er relevant
> Setter arbeidsform som påbudt felt

- src/main/kotlin/no/nav/helse/App.kt
- src/main/kotlin/no/nav/helse/soknad/SøknadApis.kt
> Verifiserer at vedleggene eksisterer på valideringsendepunkt.

- src/main/kotlin/no/nav/helse/redis/RedisConfig.kt
- src/test/kotlin/no/nav/helse/ApplicationTest.kt
- src/test/kotlin/no/nav/helse/ApplicationWithMocks.kt
- src/test/kotlin/no/nav/helse/TestConfiguration.kt
- src/test/kotlin/no/nav/helse/mellomlagring/MellomlagringTest.kt
> Fikser redisHost for redis klient i test

- .github/workflows/build-and-deploy.yml
> Oppdaterer cache og setup-java.

- build.gradle.kts
- src/main/kotlin/no/nav/helse/k9format/K9Arbeidstid.kt
- src/main/kotlin/no/nav/helse/k9format/K9Format.kt
- src/main/kotlin/no/nav/helse/soknad/Søknad.kt
- src/test/kotlin/no/nav/helse/SerDesTest.kt
- src/test/kotlin/no/nav/helse/SøknadUtils.kt
- src/test/kotlin/no/nav/helse/k9format/K9FormatTest.kt
> Oppgraderer k9-format og refaktorer mapping.

- src/main/kotlin/no/nav/helse/k9format/K9Format.kt
> Fikser mapping av beredskap

- src/main/kotlin/no/nav/helse/k9format/K9ArbeidAktivitet.kt
- src/main/kotlin/no/nav/helse/soknad/Søknad.kt
- src/test/kotlin/no/nav/helse/SerDesTest.kt
> Legger til sluttdato på frilanser

- build.gradle.kts
- src/main/kotlin/no/nav/helse/k9format/K9ArbeidAktivitet.kt
- src/main/kotlin/no/nav/helse/k9format/K9Format.kt
- src/test/kotlin/no/nav/helse/SøknadUtils.kt
- src/test/kotlin/no/nav/helse/k9format/K9FormatTest.kt
> Bumper opp k9Format og fikser Omsorg.

- src/main/kotlin/no/nav/helse/k9format/K9OpptjeningAktivitet.kt
- src/test/kotlin/no/nav/helse/k9format/K9FormatTest.kt
> Mapper på bruttoinntekt med inntektEtterEndring dersom det er varigEndring.

- nais/naiserator.yml
> Øker proxy-body-size til 100MB

- .github/workflows/build-and-deploy.yml
- build.gradle.kts
- gradle/wrapper/gradle-wrapper.properties
- src/main/kotlin/no/nav/helse/App.kt
- src/main/kotlin/no/nav/helse/Endepunkter.kt
- src/main/kotlin/no/nav/helse/arbeidsgiver/ArbeidsgiverApis.kt
- src/main/kotlin/no/nav/helse/barn/BarnApis.kt
- src/main/kotlin/no/nav/helse/mellomlagring/Mellomlagring.kt
- src/main/kotlin/no/nav/helse/soker/SøkerApis.kt
- src/main/kotlin/no/nav/helse/soknad/SøknadApis.kt
- src/main/kotlin/no/nav/helse/vedlegg/VedleggApis.kt
- src/main/kotlin/no/nav/helse/vedlegg/VedleggProblemDetails.kt
- src/test/kotlin/no/nav/helse/ApplicationTest.kt
- src/test/kotlin/no/nav/helse/mellomlagring/MellomlagringTest.kt
Closes #105
Closes #103
Closes #101
Closes #89
> Oppdaterer avhengigheter.

- src/main/kotlin/no/nav/helse/soknad/KomplettSøknad.kt
- src/main/kotlin/no/nav/helse/soknad/Søknad.kt
- src/main/kotlin/no/nav/helse/soknad/SøknadService.kt
- src/main/kotlin/no/nav/helse/soknad/SøknadValidator.kt
- src/test/kotlin/no/nav/helse/SoknadValidationTest.kt
Det er ikke alltid bruker skal svare på spørsmålet
> Setter harVærtEllerErVernepliktig som optional og fjerner validering

- build.gradle.kts
- gradle/wrapper/gradle-wrapper.properties
- src/test/kotlin/no/nav/helse/ApplicationTest.kt
- src/test/kotlin/no/nav/helse/SoknadValidationTest.kt
Erstatter junit4 med juni5.
Fjerner ubrukte repositories.
- closes #121
- closes #122 
> Oppgraderer gradle wrapper, dusseldorf-ktor og plugins.

- src/main/kotlin/no/nav/helse/k9format/K9Format.kt
- src/main/kotlin/no/nav/helse/soknad/KomplettSøknad.kt
- src/main/kotlin/no/nav/helse/soknad/Omsorgstilbud.kt
- src/main/kotlin/no/nav/helse/soknad/Søknad.kt
- src/main/kotlin/no/nav/helse/soknad/SøknadService.kt
- src/main/kotlin/no/nav/helse/soknad/SøknadValidator.kt
- src/test/kotlin/no/nav/helse/ApplicationTest.kt
- src/test/kotlin/no/nav/helse/SerDesTest.kt
- src/test/kotlin/no/nav/helse/SøknadUtils.kt
- src/test/kotlin/no/nav/helse/k9format/K9FormatTest.kt
Fjerner den gamle omsorgstilbud varianten.
Rydder opp i tester
> Fikser slik at tilsynsordning legges på K9Formatet. Samme med enkeltdager. 

- nais/dev-gcp.json
- src/test/kotlin/no/nav/helse/k9format/K9FormatTest.kt
> Legger til sif-innsyn i tillatte cors-adresser.

- src/main/kotlin/no/nav/helse/arbeidsgiver/ArbeidsgiverApis.kt
- src/main/kotlin/no/nav/helse/arbeidsgiver/ArbeidsgivereGateway.kt
- src/main/kotlin/no/nav/helse/arbeidsgiver/ArbeidsgivereService.kt
- src/main/kotlin/no/nav/helse/barn/BarnApis.kt
- src/main/kotlin/no/nav/helse/barn/BarnGateway.kt
- src/main/kotlin/no/nav/helse/barn/BarnService.kt
- src/main/kotlin/no/nav/helse/general/oppslag/K9OppslagGateway.kt
- src/main/kotlin/no/nav/helse/soker/SøkerApis.kt
- src/main/kotlin/no/nav/helse/soker/SøkerGateway.kt
- src/test/kotlin/no/nav/helse/ApplicationTest.kt
- src/test/kotlin/no/nav/helse/wiremock/WireMockStubs.kt
> Håndterer oppslag av umyndig søker.

- src/main/kotlin/no/nav/helse/arbeidsgiver/ArbeidsgiverApis.kt
- src/main/kotlin/no/nav/helse/arbeidsgiver/Arbeidsgivere.kt
- src/main/kotlin/no/nav/helse/arbeidsgiver/ArbeidsgivereGateway.kt
- src/main/kotlin/no/nav/helse/arbeidsgiver/ArbeidsgivereService.kt
- src/test/kotlin/no/nav/helse/ApplicationTest.kt
- src/test/kotlin/no/nav/helse/wiremock/ArbeidsgivereMedPrivateResponseTransformer.kt
- src/test/kotlin/no/nav/helse/wiremock/ArbeidsgivereResponseTransformer.kt
- src/test/kotlin/no/nav/helse/wiremock/WireMockStubs.kt
For å hente det må man sette paramter "private_arbeidsgivere" til true
> Legger til oppslag av private arbeidsgivere

- .github/workflows/deploy-redis.yml
- nais/naiserator.yml
- redis-config.yml
Justerer cpu for app.
Justerer minne og cpu for Redis instansen.
Deployer redis fra workflow
> Justerer reserverte ressurser

- .github/workflows/build-and-deploy.yml
- build.gradle.kts
- src/main/kotlin/no/nav/helse/k9format/K9Arbeidstid.kt
- src/main/kotlin/no/nav/helse/k9format/K9Format.kt
- src/main/kotlin/no/nav/helse/k9format/K9OpptjeningAktivitet.kt
- src/test/kotlin/no/nav/helse/ApplicationTest.kt
- Fjerner ubrukt jakarta.el bibliotek.
- closes #169
- closes #168
- closes #167
- closes #166
- closes #165
- closes #151
> Oppdaterer dusseldorf-ktor, plugins, pakker og actions.

- src/main/kotlin/no/nav/helse/k9format/K9Format.kt
- src/main/kotlin/no/nav/helse/soknad/Søknad.kt
- src/test/kotlin/no/nav/helse/SerDesTest.kt
- src/test/kotlin/no/nav/helse/SøknadUtils.kt
- src/test/kotlin/no/nav/helse/k9format/K9FormatTest.kt
- src/test/kotlin/no/nav/helse/k9format/K9FormatUtenlandsopphold.kt
> Fiks mapping av Utenlandsopphold til å ta hensyn til spesifikke opphold hvor barnet er innlagt i utenlandsoppholdet.

- .github/workflows/apply-alerts.yml
- .github/workflows/build-and-deploy.yml
- .github/workflows/deploy-redis.yml
- .github/workflows/snyk.yml
- Dockerfile
- build.gradle.kts
- gradle/wrapper/gradle-wrapper.properties
- src/test/kotlin/no/nav/helse/k9format/K9FormatUtils.kt
* Closes #220
* Closes #217
* Closes #212
* Closes #211
* Closes #221
> Oppdaterer actions, k9Format og java.

- nais/dev-gcp.json
- nais/prod-gcp.json
> Migrerer til k9-selvbetjening-oppslag i gcp

- nais/dev-gcp.json
- nais/naiserator.yml
- nais/prod-gcp.json
> Bruker service-discovery for oppslag.

- build.gradle.kts
- src/main/kotlin/no/nav/helse/App.kt
- src/main/kotlin/no/nav/helse/Configuration.kt
- src/main/kotlin/no/nav/helse/arbeidsgiver/ArbeidsgiverApis.kt
- src/main/kotlin/no/nav/helse/barn/BarnApis.kt
- src/main/kotlin/no/nav/helse/endringsmelding/EndringsmeldingApis.kt
- src/main/kotlin/no/nav/helse/general/ApplicationCallUtils.kt
- src/main/kotlin/no/nav/helse/mellomlagring/K9BrukerdialogCacheGateway.kt
- src/main/kotlin/no/nav/helse/mellomlagring/MellomlagringApis.kt
- src/main/kotlin/no/nav/helse/soker/SøkerApis.kt
- src/main/kotlin/no/nav/helse/soknad/SøknadApis.kt
- src/main/kotlin/no/nav/helse/soknad/domene/arbeid/ArbeidIPeriode.kt
- src/main/kotlin/no/nav/helse/vedlegg/VedleggApis.kt
- src/test/kotlin/no/nav/helse/ApplicationTest.kt
- src/test/kotlin/no/nav/helse/ApplicationWithMocks.kt
- src/test/kotlin/no/nav/helse/wiremock/K9BrukerdialogCacheResponseTransformer.kt
- Oppgraderer tokenSupportVersion med støtte for Ktor 2.0.
> Oppgraderer dusseldorf-ktor og dermed til Ktor 2.0.
